/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asweb.view.isc;

import asweb.control.isc.CtrlAmoMascota;
import javax.swing.*;

/**
 *
 * @author jol
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtfNombreDue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jNombreMascota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRaza = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jVacuna1 = new javax.swing.JTextField();
        jVacuna2 = new javax.swing.JTextField();
        jVacuna3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mascotas");
        setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre dueño:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 60, 150, 15);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 28, 0, 0);

        jLabel5.setText("CONTROL DE MASCOTAS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 20, 220, 15);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 270, 70, 25);

        jtfNombreDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreDueActionPerformed(evt);
            }
        });
        getContentPane().add(jtfNombreDue);
        jtfNombreDue.setBounds(130, 60, 280, 20);

        jLabel2.setText("Nombre de la mascota:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 180, 15);

        jNombreMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreMascotaActionPerformed(evt);
            }
        });
        getContentPane().add(jNombreMascota);
        jNombreMascota.setBounds(170, 100, 240, 20);

        jLabel3.setText("Raza:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 160, 15);
        getContentPane().add(jRaza);
        jRaza.setBounds(60, 140, 140, 20);

        jLabel6.setText("Cuadro de vacunación:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 220, 15);

        jLabel7.setText("Vacuna 3:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 270, 110, 15);

        jLabel8.setText("Vacuna 1:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 210, 120, 15);

        jLabel9.setText("Vacuna 2:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 240, 110, 15);
        getContentPane().add(jVacuna1);
        jVacuna1.setBounds(110, 210, 120, 19);
        getContentPane().add(jVacuna2);
        jVacuna2.setBounds(110, 240, 120, 19);
        getContentPane().add(jVacuna3);
        jVacuna3.setBounds(110, 270, 120, 19);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        CtrlAmoMascota obAM = new CtrlAmoMascota();
        
        obAM.setDuenio(this.jtfNombreDue.getText().trim());
        obAM.setMascota(this.jNombreMascota.getText().trim());
        obAM.setRaza(this.jRaza.getText().trim());
        obAM.setVacuna1(this.jVacuna1.getText().trim());
        obAM.setVacuna2(this.jVacuna2.getText().trim());
        obAM.setVacuna3(this.jVacuna3.getText().trim());
        
        
        JOptionPane.showMessageDialog(null, "DUEÑO: "+obAM.getDuenio(), "Registro de dueño:", 
                JOptionPane.INFORMATION_MESSAGE);
        
        JOptionPane.showMessageDialog(this, "MASCOTA: "+obAM.getMascota()+
                                            "\nRAZA: "+obAM.getRaza()+
                                            "\n\n== CARTILLA DE VACUNACIÓN ==\nVACUNA 1: "+obAM.getVacuna1()+
                                            "\nVACUNA 2: "+obAM.getVacuna2()+
                                            "\nVACUNA 3: "+obAM.getVacuna3()
                , "Registro de dueño:",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfNombreDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreDueActionPerformed
       
    }//GEN-LAST:event_jtfNombreDueActionPerformed

    private void jNombreMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreMascotaActionPerformed
        
    }//GEN-LAST:event_jNombreMascotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNombreMascota;
    private javax.swing.JTextField jRaza;
    private javax.swing.JTextField jVacuna1;
    private javax.swing.JTextField jVacuna2;
    private javax.swing.JTextField jVacuna3;
    private javax.swing.JTextField jtfNombreDue;
    // End of variables declaration//GEN-END:variables
}
